param(
    [switch]$Check
)

$ErrorActionPreference = 'Stop'

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
$srcRoot = Join-Path $repoRoot 'src'
$apiRoot = Join-Path $repoRoot 'api'

if (-not $Check -and -not (Test-Path $apiRoot)) {
    New-Item -ItemType Directory -Path $apiRoot | Out-Null
}

$typePattern = '^\s*public\s+(?<modifiers>(?:(?:abstract|sealed|static|readonly|partial)\s+)*)(?<kind>record\s+struct|record\s+class|ref\s+struct|record|class|struct|interface|enum|delegate)\s+(?<name>[A-Za-z_][A-Za-z0-9_]*(?:<[^>{}\r\n]+>)?)'
$namespacePattern = '^\s*namespace\s+(?<name>[^;{]+)[;{]'

function Get-TypeReview([string]$name, [string]$kind, [string]$modifiers) {
    $flags = @()
    if ($name -notmatch '^[A-Z][A-Za-z0-9_]*(?:<[^>]+>)?$') {
        $flags += 'review-naming'
    }

    if ($kind -eq 'class' -and $modifiers -notmatch '\bsealed\b' -and $modifiers -notmatch '\bstatic\b' -and $modifiers -notmatch '\babstract\b') {
        $flags += 'review-unsealed-class'
    }

    if (($kind -eq 'struct' -or $kind -eq 'ref struct') -and $modifiers -notmatch '\breadonly\b') {
        $flags += 'review-mutable-struct'
    }

    if ($kind -eq 'record struct' -and $modifiers -notmatch '\breadonly\b') {
        $flags += 'review-mutable-record-struct'
    }

    if ($kind -eq 'interface' -or $modifiers -match '\babstract\b') {
        $flags += 'review-contract'
    }

    if ($flags.Count -eq 0) {
        return 'stable-shape'
    }

    return $flags -join ','
}

function Get-PublicTypes([string]$projectPath) {
    $projectName = Split-Path $projectPath -Leaf
    $files = Get-ChildItem -Path $projectPath -Recurse -Filter '*.cs' |
        Where-Object { $_.FullName -notmatch '\\(bin|obj)\\' } |
        Sort-Object FullName

    foreach ($file in $files) {
        $relativePath = [IO.Path]::GetRelativePath($projectPath, $file.FullName).Replace('\', '/')
        $namespace = ''

        foreach ($line in Get-Content -Path $file.FullName) {
            $namespaceMatch = [regex]::Match($line, $namespacePattern)
            if ($namespaceMatch.Success) {
                $namespace = $namespaceMatch.Groups['name'].Value.Trim()
                continue
            }

            $typeMatch = [regex]::Match($line, $typePattern)
            if (-not $typeMatch.Success) {
                continue
            }

            $modifiers = $typeMatch.Groups['modifiers'].Value.Trim()
            $kind = $typeMatch.Groups['kind'].Value.Trim()
            $name = $typeMatch.Groups['name'].Value.Trim()
            $fullName = if ([string]::IsNullOrWhiteSpace($namespace)) { $name } else { "$namespace.$name" }
            $declaration = "public $modifiers $kind".Replace('  ', ' ').Trim()
            $review = Get-TypeReview $name $kind $modifiers

            [PSCustomObject]@{
                Project = $projectName
                FullName = $fullName
                Declaration = $declaration
                Review = $review
                File = $relativePath
            }
        }
    }
}

$failed = $false

Get-ChildItem -Path $srcRoot -Directory | Sort-Object Name | ForEach-Object {
    $projectName = $_.Name
    $baselinePath = Join-Path $apiRoot "PublicTypes.$projectName.txt"
    $types = @(Get-PublicTypes $_.FullName | Sort-Object FullName, File)
    $lines = @(
        "# Public type baseline for $projectName",
        "# Generated by scripts/Export-PublicApi.ps1.",
        "# Review flags: review-unsealed-class, review-mutable-struct, review-mutable-record-struct, review-contract, stable-shape.",
        ''
    )
    $lines += $types | ForEach-Object {
        "$($_.FullName) | $($_.Declaration) | $($_.Review) | $($_.File)"
    }

    if ($Check) {
        if (-not (Test-Path $baselinePath)) {
            Write-Error "Missing public API baseline: $baselinePath"
            $failed = $true
            return
        }

        $expected = Get-Content -Path $baselinePath
        $actual = $lines
        if (Compare-Object -ReferenceObject $expected -DifferenceObject $actual) {
            Write-Error "Public API baseline is out of date: $baselinePath"
            $failed = $true
        }

        return
    }

    Set-Content -Path $baselinePath -Value $lines
}

if ($failed) {
    exit 1
}
