using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Bezoro.ECS.SourceGen.Generators;

[Generator]
public sealed class ComponentCatalogGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var components = context.CompilationProvider.Select(static (compilation, _) =>
		{
			var result = new List<string>();
			CollectComponents(compilation.Assembly.GlobalNamespace, result);
			result.Sort(StringComparer.Ordinal);
			return result;
		});

		context.RegisterSourceOutput(components, static (productionContext, componentTypes) =>
		{
			var builder = new StringBuilder();
			builder.AppendLine("// <auto-generated />");
			builder.AppendLine("namespace Bezoro.ECS.Generated;");
			builder.AppendLine();
			builder.AppendLine("internal static class ComponentTypeCatalog");
			builder.AppendLine("{");
			builder.AppendLine("    internal static void RegisterAll(global::Bezoro.ECS.Internal.ComponentTypeRegistry registry)");
			builder.AppendLine("    {");
			foreach (var typeName in componentTypes)
				builder.Append("        registry.GetOrCreate(typeof(").Append(typeName).AppendLine("));");
			builder.AppendLine("    }");
			builder.AppendLine("}");

			productionContext.AddSource("ComponentTypeCatalog.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
		});
	}

	private static void CollectComponents(INamespaceSymbol namespaceSymbol, ICollection<string> output)
	{
		foreach (var member in namespaceSymbol.GetMembers())
		{
			if (member is INamespaceSymbol ns)
			{
				CollectComponents(ns, output);
				continue;
			}

			if (member is not INamedTypeSymbol type || type.TypeKind != TypeKind.Struct)
				continue;

			if (!ImplementsComponent(type))
				continue;

			output.Add(type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
		}
	}

	private static bool ImplementsComponent(INamedTypeSymbol symbol)
	{
		for (var i = 0; i < symbol.AllInterfaces.Length; i++)
		{
			if (symbol.AllInterfaces[i].ToDisplayString() == "Bezoro.ECS.Abstractions.IComponent")
				return true;
		}

		return false;
	}
}
