using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Bezoro.ECS.SourceGen.Generators;

[Generator]
public sealed class ComponentCatalogGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var components = context.CompilationProvider.Select(static (compilation, _) =>
			{
				var result = new List<string>();
				CollectComponents(compilation.Assembly.GlobalNamespace, result);
				result.Sort(StringComparer.Ordinal);
				return result;
			}
		);

		context.RegisterSourceOutput(
			components, static (productionContext, componentTypes) =>
			{
				var builder = new StringBuilder();
				builder.AppendLine("// <auto-generated />");
				builder.AppendLine("namespace Bezoro.ECS.Generated;");
				builder.AppendLine();
				builder.AppendLine("internal static class ComponentTypeCatalog");
				builder.AppendLine("{");
				builder.AppendLine(
					"    internal static void RegisterAll(global::Bezoro.ECS.Internal.ComponentTypeRegistry registry)"
				);

				builder.AppendLine("    {");
				foreach (string? typeName in componentTypes)
					builder.Append("        registry.GetOrCreate(typeof(").Append(typeName).AppendLine("));");

				builder.AppendLine("    }");
				builder.AppendLine("}");

				productionContext.AddSource(
					"ComponentTypeCatalog.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8)
				);
			}
		);
	}

	private static void CollectComponents(INamespaceSymbol namespaceSymbol, ICollection<string> output)
	{
		// Component types are now lazily registered via GetOrCreate at first use.
		// No compile-time discovery is needed without the IComponent marker interface.
	}
}
