using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Bezoro.ECS.SourceGen.Generators;

[Generator]
public sealed class ForEachJobSourceGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var jobs = context.CompilationProvider.Select(static (compilation, _) =>
		{
			var models = new List<JobModel>();
			CollectJobs(compilation.Assembly.GlobalNamespace, models);
			return models;
		});

		context.RegisterSourceOutput(jobs, static (productionContext, models) =>
		{
			for (var i = 0; i < models.Count; i++)
			{
				var model = models[i];
				var source = BuildSource(model);
				productionContext.AddSource(model.HintName, SourceText.From(source, Encoding.UTF8));
			}
		});
	}

	private static void CollectJobs(INamespaceSymbol namespaceSymbol, ICollection<JobModel> models)
	{
		foreach (var member in namespaceSymbol.GetMembers())
		{
			if (member is INamespaceSymbol ns)
			{
				CollectJobs(ns, models);
				continue;
			}

			if (member is not INamedTypeSymbol type || type.TypeKind != TypeKind.Struct)
				continue;

			if (type.ContainingType is not null)
				continue;

			if (!TryGetForEachTypes(type, out var firstType, out var secondType))
				continue;

			var namespaceName = type.ContainingNamespace.IsGlobalNamespace
				? string.Empty
				: type.ContainingNamespace.ToDisplayString();
			string jobType = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
			string first = firstType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
			string second = secondType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
			string hintName = jobType
				.Replace("global::", string.Empty)
				.Replace('.', '_')
				.Replace('<', '_')
				.Replace('>', '_') + ".ForEachJob.g.cs";

			models.Add(new JobModel(namespaceName, type.Name, jobType, first, second, hintName));
		}
	}

	private static bool TryGetForEachTypes(INamedTypeSymbol type, out ITypeSymbol firstType, out ITypeSymbol secondType)
	{
		for (var i = 0; i < type.AllInterfaces.Length; i++)
		{
			var iface = type.AllInterfaces[i];
			if (!IsForEachInterface(iface.OriginalDefinition))
				continue;

			firstType = iface.TypeArguments[0];
			secondType = iface.TypeArguments[1];
			return true;
		}

		firstType = null!;
		secondType = null!;
		return false;
	}

	private static bool IsForEachInterface(INamedTypeSymbol symbol) =>
		symbol.MetadataName == "IForEach`2" &&
		symbol.ContainingNamespace.ToDisplayString() == "Bezoro.ECS.Abstractions";

	private static string BuildSource(JobModel model)
	{
		var builder = new StringBuilder();
		builder.AppendLine("// <auto-generated />");

		if (!string.IsNullOrEmpty(model.Namespace))
		{
			builder.Append("namespace ").Append(model.Namespace).AppendLine(";");
			builder.AppendLine();
		}

		builder.Append("internal static class ").Append(model.TypeName).AppendLine("ForEachExtensions");
		builder.AppendLine("{");
		builder.Append("    public static void ForEach(this global::Bezoro.ECS.Types.Query query, ").Append(model.JobType).AppendLine(" job)");
		builder.AppendLine("    {");
		builder.AppendLine("        if (query is null) throw new global::System.ArgumentNullException(nameof(query));");
		builder.Append("        query.ForEach<").Append(model.JobType).Append(", ").Append(model.FirstType).Append(", ").Append(model.SecondType).AppendLine(">(job);");
		builder.AppendLine("    }");
		builder.AppendLine("}");

		return builder.ToString();
	}

	private sealed class JobModel
	{
		public JobModel(string typeNamespace, string typeName, string jobType, string firstType, string secondType, string hintName)
		{
			Namespace = typeNamespace;
			TypeName = typeName;
			JobType = jobType;
			FirstType = firstType;
			SecondType = secondType;
			HintName = hintName;
		}

		public string Namespace { get; }
		public string TypeName { get; }
		public string JobType { get; }
		public string FirstType { get; }
		public string SecondType { get; }
		public string HintName { get; }
	}
}
