using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Bezoro.ECS.SourceGen.Generators;

[Generator]
public sealed class ForEachJobSourceGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var jobs = context.CompilationProvider.Select(static (compilation, _) =>
			{
				var models = new List<JobModel>();
				CollectJobs(compilation.Assembly.GlobalNamespace, models);
				return models;
			}
		);

		context.RegisterSourceOutput(
			jobs, static (productionContext, models) =>
			{
				for (var i = 0; i < models.Count; i++)
				{
					var    model  = models[i];
					string source = BuildSource(model);
					productionContext.AddSource(model.HintName, SourceText.From(source, Encoding.UTF8));
				}
			}
		);
	}

	private static bool IsAccessibleFromGeneratedCode(INamedTypeSymbol type)
	{
		if (!IsTypeAccessibilitySupported(type.DeclaredAccessibility))
			return false;

		for (var containing = type.ContainingType; containing is { }; containing = containing.ContainingType)
		{
			if (!IsTypeAccessibilitySupported(containing.DeclaredAccessibility))
				return false;
		}

		return true;
	}

	private static bool IsTypeAccessibilitySupported(Accessibility accessibility) =>
		accessibility == Accessibility.Public || accessibility == Accessibility.Internal;

	private static bool TryGetForEachTypes(INamedTypeSymbol type, out ITypeSymbol[] componentTypes, out bool isEntityAware)
	{
		INamedTypeSymbol? selected      = null;
		var               selectedArity = 0;
		isEntityAware = false;

		for (var i = 0; i < type.AllInterfaces.Length; i++)
		{
			var iface = type.AllInterfaces[i];
			if (!TryGetSupportedArity(iface.OriginalDefinition, out int arity))
				continue;

			if (arity > selectedArity)
			{
				selected      = iface;
				selectedArity = arity;
				isEntityAware = iface.OriginalDefinition.MetadataName.StartsWith("IForEachEntity`", StringComparison.Ordinal);
			}
		}

		if (selected is null)
		{
			componentTypes = [];
			isEntityAware  = false;
			return false;
		}

		componentTypes = new ITypeSymbol[selected.TypeArguments.Length];
		for (var i = 0; i < selected.TypeArguments.Length; i++)
			componentTypes[i] = selected.TypeArguments[i];

		return true;
	}

	private static bool TryGetSupportedArity(INamedTypeSymbol symbol, out int arity)
	{
		arity = 0;
		if (symbol.ContainingNamespace.ToDisplayString() != "Bezoro.ECS.Abstractions")
			return false;

		string metadataName = symbol.MetadataName;
		string prefix;
		if (metadataName.StartsWith("IForEachEntity`", StringComparison.Ordinal))
			prefix = "IForEachEntity`";
		else if (metadataName.StartsWith("IForEach`", StringComparison.Ordinal))
			prefix = "IForEach`";
		else
			return false;

		string arityText = metadataName.Substring(prefix.Length);
		if (!int.TryParse(arityText, out arity))
			return false;

		return arity is >= 1 and <= 4;
	}

	private static string BuildSource(JobModel model)
	{
		var builder = new StringBuilder();
		builder.AppendLine("// <auto-generated />");

		if (!string.IsNullOrEmpty(model.Namespace))
		{
			builder.Append("namespace ").Append(model.Namespace).AppendLine(";");
			builder.AppendLine();
		}

		builder.Append("internal static class ").Append(model.GeneratedTypeName).AppendLine();
		builder.AppendLine("{");
		builder.Append("    public static void Run(this global::Bezoro.ECS.Types.QueryCursor cursor, ")
			   .Append(model.JobType).AppendLine(" job)");
		builder.AppendLine("    {");
		builder.Append("        cursor.").Append(model.IsEntityAware ? "RunEntity<" : "Run<").Append(model.JobType);
		for (var i = 0; i < model.ComponentTypes.Length; i++)
			builder.Append(", ").Append(model.ComponentTypes[i]);

		builder.AppendLine(">(job);");
		builder.AppendLine("    }");
		builder.AppendLine();
		builder.Append(
			"    public static void Run<TSpec>(this global::Bezoro.ECS.Types.QueryView<TSpec> query, "
		).Append(model.JobType).AppendLine(" job)");
		builder.AppendLine("        where TSpec : struct, global::Bezoro.ECS.Abstractions.ICompiledQuerySpec");
		builder.AppendLine("    {");
		builder.Append("        query.").Append(model.IsEntityAware ? "RunEntity<" : "Run<").Append(model.JobType);
		for (var i = 0; i < model.ComponentTypes.Length; i++)
			builder.Append(", ").Append(model.ComponentTypes[i]);

		builder.AppendLine(">(job);");
		builder.AppendLine("    }");
		builder.AppendLine();
		builder.Append(
			"    public static void RunParallel<TSpec>(this global::Bezoro.ECS.Types.QueryView<TSpec> query, "
		).Append(model.JobType).AppendLine(" job, int? degreeOfParallelism = null)");
		builder.AppendLine("        where TSpec : struct, global::Bezoro.ECS.Abstractions.ICompiledQuerySpec");
		builder.AppendLine("    {");
		builder.Append("        query.").Append(model.IsEntityAware ? "RunParallelEntity<" : "RunParallel<").Append(model.JobType);
		for (var i = 0; i < model.ComponentTypes.Length; i++)
			builder.Append(", ").Append(model.ComponentTypes[i]);

		builder.AppendLine(">(job, degreeOfParallelism);");
		builder.AppendLine("    }");
		builder.AppendLine();
		builder.Append(
			"    public static void Run<TSpec>(this global::Bezoro.ECS.Services.World world, global::Bezoro.ECS.Types.QueryHandle<TSpec> handle, "
		).Append(model.JobType).AppendLine(" job)");

		builder.AppendLine("        where TSpec : struct, global::Bezoro.ECS.Abstractions.ICompiledQuerySpec");
		builder.AppendLine("    {");
		builder.Append("        world.").Append(model.IsEntityAware ? "RunEntity<TSpec, " : "Run<TSpec, ").Append(model.JobType);
		for (var i = 0; i < model.ComponentTypes.Length; i++)
			builder.Append(", ").Append(model.ComponentTypes[i]);

		builder.AppendLine(">(handle, job);");
		builder.AppendLine("    }");
		builder.AppendLine("}");

		return builder.ToString();
	}

	private static string SanitizeTypeName(string typeName)
	{
		var builder = new StringBuilder(typeName.Length);
		for (var i = 0; i < typeName.Length; i++)
		{
			char ch = typeName[i];
			builder.Append(char.IsLetterOrDigit(ch) ? ch : '_');
		}

		return builder.ToString();
	}

	private static void CollectJobs(INamespaceSymbol namespaceSymbol, ICollection<JobModel> models)
	{
		foreach (var member in namespaceSymbol.GetMembers())
		{
			if (member is INamespaceSymbol ns)
			{
				CollectJobs(ns, models);
				continue;
			}

			if (member is INamedTypeSymbol type)
				CollectJobs(type, models);
		}
	}

	private static void CollectJobs(INamedTypeSymbol type, ICollection<JobModel> models)
	{
		if (type.TypeKind == TypeKind.Struct &&
			IsAccessibleFromGeneratedCode(type) &&
			TryGetForEachTypes(type, out var componentTypes, out bool isEntityAware))
		{
			string namespaceName = type.ContainingNamespace.IsGlobalNamespace
									   ? string.Empty
									   : type.ContainingNamespace.ToDisplayString();

			string jobType            = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
			var    componentTypeNames = new string[componentTypes.Length];
			for (var i = 0; i < componentTypes.Length; i++)
				componentTypeNames[i] = componentTypes[i].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

			string sanitizedName     = SanitizeTypeName(jobType);
			string generatedTypeName = sanitizedName + "ForEachExtensions";
			string hintName          = sanitizedName + ".ForEachJob.g.cs";
			models.Add(new(namespaceName, generatedTypeName, jobType, componentTypeNames, hintName, isEntityAware));
		}

		var nestedTypes = type.GetTypeMembers();
		for (var i = 0; i < nestedTypes.Length; i++)
			CollectJobs(nestedTypes[i], models);
	}

	private sealed class JobModel(
		string   typeNamespace,
		string   generatedTypeName,
		string   jobType,
		string[] componentTypes,
		string   hintName,
		bool     isEntityAware
	)
	{
		public string GeneratedTypeName { get; } = generatedTypeName;
		public string HintName          { get; } = hintName;
		public bool   IsEntityAware     { get; } = isEntityAware;
		public string JobType           { get; } = jobType;

		public string   Namespace      { get; } = typeNamespace;
		public string[] ComponentTypes { get; } = componentTypes;
	}
}
