using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Bezoro.ECS.SourceGen.Generators;

[Generator]
public sealed class ForEachJobSourceGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var jobs = context.CompilationProvider.Select(static (compilation, _) =>
		{
			var models = new List<JobModel>();
			CollectJobs(compilation.Assembly.GlobalNamespace, models);
			return models;
		});

		context.RegisterSourceOutput(jobs, static (productionContext, models) =>
		{
			for (var i = 0; i < models.Count; i++)
			{
				var model = models[i];
				var source = BuildSource(model);
				productionContext.AddSource(model.HintName, SourceText.From(source, Encoding.UTF8));
			}
		});
	}

	private static void CollectJobs(INamespaceSymbol namespaceSymbol, ICollection<JobModel> models)
	{
		foreach (var member in namespaceSymbol.GetMembers())
		{
			if (member is INamespaceSymbol ns)
			{
				CollectJobs(ns, models);
				continue;
			}

			if (member is INamedTypeSymbol type)
				CollectJobs(type, models);
		}
	}

	private static void CollectJobs(INamedTypeSymbol type, ICollection<JobModel> models)
	{
		if (type.TypeKind == TypeKind.Struct &&
		    IsAccessibleFromGeneratedCode(type) &&
		    TryGetForEachTypes(type, out var firstType, out var secondType))
		{
			var namespaceName = type.ContainingNamespace.IsGlobalNamespace
				? string.Empty
				: type.ContainingNamespace.ToDisplayString();
			string jobType = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
			string first = firstType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
			string second = secondType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
			string sanitizedName = SanitizeTypeName(jobType);
			string generatedTypeName = sanitizedName + "ForEachExtensions";
			string hintName = sanitizedName + ".ForEachJob.g.cs";
			models.Add(new JobModel(namespaceName, generatedTypeName, jobType, first, second, hintName));
		}

		var nestedTypes = type.GetTypeMembers();
		for (var i = 0; i < nestedTypes.Length; i++)
			CollectJobs(nestedTypes[i], models);
	}

	private static bool TryGetForEachTypes(INamedTypeSymbol type, out ITypeSymbol firstType, out ITypeSymbol secondType)
	{
		for (var i = 0; i < type.AllInterfaces.Length; i++)
		{
			var iface = type.AllInterfaces[i];
			if (!IsForEachInterface(iface.OriginalDefinition))
				continue;

			firstType = iface.TypeArguments[0];
			secondType = iface.TypeArguments[1];
			return true;
		}

		firstType = null!;
		secondType = null!;
		return false;
	}

	private static bool IsForEachInterface(INamedTypeSymbol symbol) =>
		symbol.MetadataName == "IForEach`2" &&
		symbol.ContainingNamespace.ToDisplayString() == "Bezoro.ECS.Abstractions";

	private static bool IsAccessibleFromGeneratedCode(INamedTypeSymbol type)
	{
		if (!IsTypeAccessibilitySupported(type.DeclaredAccessibility))
			return false;

		for (var containing = type.ContainingType; containing is not null; containing = containing.ContainingType)
		{
			if (!IsTypeAccessibilitySupported(containing.DeclaredAccessibility))
				return false;
		}

		return true;
	}

	private static bool IsTypeAccessibilitySupported(Accessibility accessibility) =>
		accessibility == Accessibility.Public || accessibility == Accessibility.Internal;

	private static string SanitizeTypeName(string typeName)
	{
		var builder = new StringBuilder(typeName.Length);
		for (var i = 0; i < typeName.Length; i++)
		{
			char ch = typeName[i];
			builder.Append(char.IsLetterOrDigit(ch) ? ch : '_');
		}

		return builder.ToString();
	}

	private static string BuildSource(JobModel model)
	{
		var builder = new StringBuilder();
		builder.AppendLine("// <auto-generated />");

		if (!string.IsNullOrEmpty(model.Namespace))
		{
			builder.Append("namespace ").Append(model.Namespace).AppendLine(";");
			builder.AppendLine();
		}

		builder.Append("internal static class ").Append(model.GeneratedTypeName).AppendLine();
		builder.AppendLine("{");
		builder.Append("    public static void ForEach(this global::Bezoro.ECS.Types.Query query, ").Append(model.JobType).AppendLine(" job)");
		builder.AppendLine("    {");
		builder.AppendLine("        if (query is null) throw new global::System.ArgumentNullException(nameof(query));");
		builder.Append("        query.ForEach<").Append(model.JobType).Append(", ").Append(model.FirstType).Append(", ").Append(model.SecondType).AppendLine(">(job);");
		builder.AppendLine("    }");
		builder.AppendLine("}");

		return builder.ToString();
	}

	private sealed class JobModel
	{
		public JobModel(string typeNamespace, string generatedTypeName, string jobType, string firstType, string secondType, string hintName)
		{
			Namespace = typeNamespace;
			GeneratedTypeName = generatedTypeName;
			JobType = jobType;
			FirstType = firstType;
			SecondType = secondType;
			HintName = hintName;
		}

		public string Namespace { get; }
		public string GeneratedTypeName { get; }
		public string JobType { get; }
		public string FirstType { get; }
		public string SecondType { get; }
		public string HintName { get; }
	}
}
