using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Bezoro.ECS.SourceGen.Generators;

[Generator]
public sealed class QuerySourceGenerator : IIncrementalGenerator
{
	private const string QueryAttributeName = "Bezoro.ECS.Attributes.QueryAttribute";
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var queryModels = context.SyntaxProvider.ForAttributeWithMetadataName(
			QueryAttributeName,
			static (node, _) => node is StructDeclarationSyntax,
			static (syntaxContext, _) => CreateModel((INamedTypeSymbol)syntaxContext.TargetSymbol))
			.Where(static model => model is not null)
			.Select(static (model, _) => model!);

		context.RegisterSourceOutput(queryModels, static (productionContext, model) =>
		{
			var source = BuildSource(model);
			productionContext.AddSource(model.HintName, SourceText.From(source, Encoding.UTF8));
		});
	}

	private static QueryModel? CreateModel(INamedTypeSymbol symbol)
	{
		if (symbol.TypeKind != TypeKind.Struct)
			return null;

		var filters = new FilterModel([], [], [], [], []);

		foreach (var attribute in symbol.GetAttributes())
		{
			var attributeClass = attribute.AttributeClass;
			if (attributeClass is null) continue;

			var namespaceName = attributeClass.ContainingNamespace.ToDisplayString();
			if (namespaceName != "Bezoro.ECS.Attributes")
				continue;

			if (attributeClass.Name == "AllAttribute")
			{
				if (attributeClass.TypeArguments.Length == 1)
					filters.All.Add(ToFullyQualified(attributeClass.TypeArguments[0]));
			}
			else if (attributeClass.Name == "NoneAttribute")
			{
				if (attributeClass.TypeArguments.Length == 1)
					filters.None.Add(ToFullyQualified(attributeClass.TypeArguments[0]));
			}
			else if (attributeClass.Name == "AnyAttribute")
			{
				if (attributeClass.TypeArguments.Length == 2)
					filters.AnyPairs.Add((
						ToFullyQualified(attributeClass.TypeArguments[0]),
						ToFullyQualified(attributeClass.TypeArguments[1])));
			}
			else if (attributeClass.Name == "OptionalAttribute")
			{
				if (attributeClass.TypeArguments.Length == 1)
					filters.Optional.Add(ToFullyQualified(attributeClass.TypeArguments[0]));
			}
			else if (attributeClass.Name == "ChangedAttribute")
			{
				if (attributeClass.TypeArguments.Length == 1)
					filters.Changed.Add(ToFullyQualified(attributeClass.TypeArguments[0]));
			}
		}

		var typeNamespace = symbol.ContainingNamespace.IsGlobalNamespace
			? string.Empty
			: symbol.ContainingNamespace.ToDisplayString();
		var generatedTypeName = symbol.Name + "Generated";
		var hintName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
			.Replace("global::", string.Empty)
			.Replace('<', '_')
			.Replace('>', '_')
			.Replace('.', '_') + ".Query.g.cs";

		return new QueryModel(typeNamespace, symbol.Name, generatedTypeName, hintName, filters);
	}

	private static string BuildSource(QueryModel model)
	{
		var builder = new StringBuilder();
		builder.AppendLine("// <auto-generated />");
		builder.AppendLine("using Bezoro.ECS.Abstractions;");
		builder.AppendLine("using Bezoro.ECS.Types;");

		if (!string.IsNullOrEmpty(model.Namespace))
		{
			builder.Append("namespace ").Append(model.Namespace).AppendLine(";");
			builder.AppendLine();
		}

		builder.Append("public static class ").Append(model.GeneratedTypeName).AppendLine();
		builder.AppendLine("{");
		builder.Append("    public static global::Bezoro.ECS.Types.Query Create(IWorld world)").AppendLine();
		builder.AppendLine("    {");
		builder.AppendLine("        if (world is null) throw new System.ArgumentNullException(nameof(world));");
		builder.AppendLine("        var query = world.Query();");

		foreach (var typeName in model.Filters.All.Distinct())
			builder.Append("        query = query.All<").Append(typeName).AppendLine(">();");

		foreach (var typeName in model.Filters.None.Distinct())
			builder.Append("        query = query.None<").Append(typeName).AppendLine(">();");

		foreach (var pair in model.Filters.AnyPairs.Distinct())
			builder.Append("        query = query.Any<").Append(pair.First).Append(", ").Append(pair.Second).AppendLine(">();");

		foreach (var typeName in model.Filters.Optional.Distinct())
			builder.Append("        query = query.Optional<").Append(typeName).AppendLine(">();");

		foreach (var typeName in model.Filters.Changed.Distinct())
			builder.Append("        query = query.Changed<").Append(typeName).AppendLine(">();");

		builder.AppendLine("        return query;");
		builder.AppendLine("    }");
		builder.AppendLine();
		builder.AppendLine("    public static void ForEach<T1>(IWorld world, global::Bezoro.ECS.Types.Query.RefAction<T1> action)");
		builder.AppendLine("        where T1 : struct, global::Bezoro.ECS.Abstractions.IComponent");
		builder.AppendLine("    {");
		builder.AppendLine("        if (action is null) throw new System.ArgumentNullException(nameof(action));");
		builder.AppendLine("        var query = Create(world).All<T1>();");
		builder.AppendLine("        query.ForEach(action);");
		builder.AppendLine("    }");
		builder.AppendLine();
		builder.AppendLine("    public static void ForEach<T1, T2>(IWorld world, global::Bezoro.ECS.Types.Query.RefInAction<T1, T2> action)");
		builder.AppendLine("        where T1 : struct, global::Bezoro.ECS.Abstractions.IComponent");
		builder.AppendLine("        where T2 : struct, global::Bezoro.ECS.Abstractions.IComponent");
		builder.AppendLine("    {");
		builder.AppendLine("        if (action is null) throw new System.ArgumentNullException(nameof(action));");
		builder.AppendLine("        var query = Create(world).All<T1>().All<T2>();");
		builder.AppendLine("        query.ForEach(action);");
		builder.AppendLine("    }");
		builder.AppendLine("}");
		return builder.ToString();
	}

	private static string ToFullyQualified(ITypeSymbol symbol) =>
		symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

	private sealed class QueryModel
	{
		public QueryModel(string typeNamespace, string typeName, string generatedTypeName, string hintName, FilterModel filters)
		{
			Namespace = typeNamespace;
			TypeName = typeName;
			GeneratedTypeName = generatedTypeName;
			HintName = hintName;
			Filters = filters;
		}

		public string Namespace { get; }
		public string TypeName { get; }
		public string GeneratedTypeName { get; }
		public string HintName { get; }
		public FilterModel Filters { get; }
	}

	private sealed class FilterModel
	{
		public FilterModel(
			List<string> all,
			List<string> none,
			List<(string First, string Second)> anyPairs,
			List<string> optional,
			List<string> changed)
		{
			All = all;
			None = none;
			AnyPairs = anyPairs;
			Optional = optional;
			Changed = changed;
		}

		public List<string> All { get; }
		public List<string> None { get; }
		public List<(string First, string Second)> AnyPairs { get; }
		public List<string> Optional { get; }
		public List<string> Changed { get; }
	}
}
