using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Bezoro.ECS.SourceGen.Generators;

[Generator]
public sealed class SystemMetadataGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var systems = context.CompilationProvider.Select(static (compilation, _) =>
		{
			var result = new List<SystemModel>();
			CollectSystems(compilation.Assembly.GlobalNamespace, result);
			return result.OrderBy(static s => s.SystemType, StringComparer.Ordinal).ToArray();
		});

		context.RegisterSourceOutput(systems, static (productionContext, models) =>
		{
			var builder = new StringBuilder();
			builder.AppendLine("// <auto-generated />");
			builder.AppendLine("namespace Bezoro.ECS.Generated;");
			builder.AppendLine();
			builder.AppendLine("internal static class GeneratedSystemMetadata");
			builder.AppendLine("{");
			builder.AppendLine("    internal static global::Bezoro.ECS.Types.SystemMetadata[] All => new global::Bezoro.ECS.Types.SystemMetadata[]");
			builder.AppendLine("    {");

			foreach (var model in models)
			{
				builder.AppendLine("        new global::Bezoro.ECS.Types.SystemMetadata(");
				builder.Append("            typeof(").Append(model.SystemType).AppendLine("),");
				builder.Append("            new global::System.Type[] { ");
				for (var i = 0; i < model.Reads.Count; i++)
				{
					if (i > 0) builder.Append(", ");
					builder.Append("typeof(").Append(model.Reads[i]).Append(')');
				}
				builder.AppendLine(" },");
				builder.Append("            new global::System.Type[] { ");
				for (var i = 0; i < model.Writes.Count; i++)
				{
					if (i > 0) builder.Append(", ");
					builder.Append("typeof(").Append(model.Writes[i]).Append(')');
				}
				builder.AppendLine(" },");
				builder.Append("            ").Append(model.IsExclusive ? "true" : "false").AppendLine("),");
			}

			builder.AppendLine("    }; ");
			builder.AppendLine("}");

			productionContext.AddSource("GeneratedSystemMetadata.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
		});
	}

	private static void CollectSystems(INamespaceSymbol namespaceSymbol, ICollection<SystemModel> output)
	{
		foreach (var member in namespaceSymbol.GetMembers())
		{
			if (member is INamespaceSymbol ns)
			{
				CollectSystems(ns, output);
				continue;
			}

			if (member is INamedTypeSymbol type)
				CollectSystems(type, output);
		}
	}

	private static void CollectSystems(INamedTypeSymbol type, ICollection<SystemModel> output)
	{
		if (type.TypeKind == TypeKind.Class || type.TypeKind == TypeKind.Struct)
		{
			if (ImplementsSystem(type) && IsAccessibleFromGeneratedCode(type))
				output.Add(BuildSystemModel(type));
		}

		var nestedTypes = type.GetTypeMembers();
		for (var i = 0; i < nestedTypes.Length; i++)
			CollectSystems(nestedTypes[i], output);
	}

	private static SystemModel BuildSystemModel(INamedTypeSymbol type)
	{
		var reads = new HashSet<string>(StringComparer.Ordinal);
		var writes = new HashSet<string>(StringComparer.Ordinal);
		var isExclusive = false;

		for (INamedTypeSymbol? current = type; current is not null; current = current.BaseType)
		{
			foreach (var attribute in current.GetAttributes())
			{
				var attributeClass = attribute.AttributeClass;
				if (attributeClass is null) continue;

				var namespaceName = attributeClass.ContainingNamespace.ToDisplayString();
				if (namespaceName != "Bezoro.ECS.Attributes")
					continue;

				if (attributeClass.Name == "ReadsAttribute" && attributeClass.TypeArguments.Length == 1)
					reads.Add(attributeClass.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
				else if (attributeClass.Name == "WritesAttribute" && attributeClass.TypeArguments.Length == 1)
					writes.Add(attributeClass.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
				else if (attributeClass.Name == "ExclusiveAttribute")
					isExclusive = true;
			}
		}

		return new SystemModel(
			type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
			reads.OrderBy(static x => x, StringComparer.Ordinal).ToArray(),
			writes.OrderBy(static x => x, StringComparer.Ordinal).ToArray(),
			isExclusive);
	}

	private static bool IsAccessibleFromGeneratedCode(INamedTypeSymbol type)
	{
		if (!IsTypeAccessibilitySupported(type.DeclaredAccessibility))
			return false;

		for (var containing = type.ContainingType; containing is not null; containing = containing.ContainingType)
		{
			if (!IsTypeAccessibilitySupported(containing.DeclaredAccessibility))
				return false;
		}

		return true;
	}

	private static bool IsTypeAccessibilitySupported(Accessibility accessibility) =>
		accessibility == Accessibility.Public || accessibility == Accessibility.Internal;

	private static bool ImplementsSystem(INamedTypeSymbol symbol)
	{
		for (var i = 0; i < symbol.AllInterfaces.Length; i++)
		{
			if (symbol.AllInterfaces[i].ToDisplayString() == "Bezoro.ECS.Abstractions.ISystem")
				return true;
		}

		return false;
	}

	private sealed class SystemModel
	{
		public SystemModel(string systemType, IReadOnlyList<string> reads, IReadOnlyList<string> writes, bool isExclusive)
		{
			SystemType = systemType;
			Reads = reads;
			Writes = writes;
			IsExclusive = isExclusive;
		}

		public string SystemType { get; }
		public IReadOnlyList<string> Reads { get; }
		public IReadOnlyList<string> Writes { get; }
		public bool IsExclusive { get; }
	}
}
