using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;
using Microsoft.CodeAnalysis.Text;

namespace Bezoro.ECS.SourceGen.Generators;

[Generator]
public sealed class SystemMetadataGenerator : IIncrementalGenerator
{
	private const string DIRECT_ITERATION_CONFLICT_RESOURCE_KEY = "global::Bezoro.ECS.Services.World";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var systems = context.CompilationProvider.Select(static (compilation, _) =>
			{
				var result = new List<SystemModel>();
				CollectSystems(compilation.Assembly.GlobalNamespace, compilation, result);
				return result.OrderBy(static s => s.SystemType, StringComparer.Ordinal).ToArray();
			}
		);

		context.RegisterSourceOutput(
			systems, static (productionContext, models) =>
			{
				var builder = new StringBuilder();
				builder.AppendLine("// <auto-generated />");
				builder.AppendLine("namespace Bezoro.ECS.Generated;");
				builder.AppendLine();
				builder.AppendLine("internal static class GeneratedSystemMetadata");
				builder.AppendLine("{");
				builder.AppendLine(
					"    internal static global::Bezoro.ECS.Types.SystemMetadata[] All => new global::Bezoro.ECS.Types.SystemMetadata[]"
				);

				builder.AppendLine("    {");

				foreach (var model in models)
				{
					builder.AppendLine("        new global::Bezoro.ECS.Types.SystemMetadata(");
					builder.Append("            typeof(").Append(model.SystemType).AppendLine("),");
					builder.Append("            new global::System.Type[] { ");
					for (var i = 0; i < model.Reads.Count; i++)
					{
						if (i > 0) builder.Append(", ");
						builder.Append("typeof(").Append(model.Reads[i]).Append(')');
					}

					builder.AppendLine(" },");
					builder.Append("            new global::System.Type[] { ");
					for (var i = 0; i < model.Writes.Count; i++)
					{
						if (i > 0) builder.Append(", ");
						builder.Append("typeof(").Append(model.Writes[i]).Append(')');
					}

					builder.AppendLine(" },");
					builder.Append("            new global::System.Type[] { ");
					for (var i = 0; i < model.ReadResources.Count; i++)
					{
						if (i > 0) builder.Append(", ");
						builder.Append("typeof(").Append(model.ReadResources[i]).Append(')');
					}

					builder.AppendLine(" },");
					builder.Append("            new global::System.Type[] { ");
					for (var i = 0; i < model.WriteResources.Count; i++)
					{
						if (i > 0) builder.Append(", ");
						builder.Append("typeof(").Append(model.WriteResources[i]).Append(')');
					}

					builder.AppendLine(" },");
					builder.Append("            ").Append(model.IsExclusive ? "true" : "false").AppendLine("),");
				}

				builder.AppendLine("    }; ");
				builder.AppendLine("}");

				productionContext.AddSource(
					"GeneratedSystemMetadata.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8)
				);
			}
		);
	}

	private static bool HasReadOnlyQueryViewForEachDelegate(IMethodSymbol method)
	{
		if (method.Parameters.Length != 1)
			return false;

		return method.Parameters[0].Type is INamedTypeSymbol parameterType &&
			   parameterType.Name == "EntityInAction" &&
			   parameterType.ContainingType is INamedTypeSymbol containingType &&
			   containingType.Name == "QueryView" &&
			   containingType.ContainingNamespace.ToDisplayString() == "Bezoro.ECS.Types";
	}

	private static bool ImplementsSystem(INamedTypeSymbol symbol)
	{
		for (var i = 0; i < symbol.AllInterfaces.Length; i++)
		{
			if (symbol.AllInterfaces[i].ToDisplayString() == "Bezoro.ECS.Abstractions.ISystem")
				return true;
		}

		return false;
	}

	private static bool IsAccessibleFromGeneratedCode(INamedTypeSymbol type)
	{
		if (!IsTypeAccessibilitySupported(type.DeclaredAccessibility))
			return false;

		for (var containing = type.ContainingType; containing is { }; containing = containing.ContainingType)
		{
			if (!IsTypeAccessibilitySupported(containing.DeclaredAccessibility))
				return false;
		}

		return true;
	}

	private static bool IsIterationMethodName(string methodName) =>
		methodName == "ForEach" ||
		methodName == "ForEachRw" ||
		methodName == "ForEachRW" ||
		methodName == "Run" ||
		methodName == "RunParallel";

	private static bool IsQueryHandleType(ITypeSymbol type) =>
		type is INamedTypeSymbol named &&
		named.Name == "QueryHandle" &&
		named.ContainingNamespace.ToDisplayString() == "Bezoro.ECS.Types";

	private static bool IsReadWriteForEachMethodName(string methodName) =>
		methodName == "ForEachRw" || methodName == "ForEachRW";

	private static bool IsTypeAccessibilitySupported(Accessibility accessibility) =>
		accessibility == Accessibility.Public || accessibility == Accessibility.Internal;

	private static bool IsTypeName(ITypeSymbol? type, string expected) =>
		type is { } && type.ToDisplayString() == expected;

	private static bool RequiresDirectIterationConflict(IterationTarget target) => false;

	private static bool TryGetComponentTypesFromGenericArguments(
		IMethodSymbol     method,
		IterationTarget   target,
		out ITypeSymbol[] componentTypes)
	{
		componentTypes = [];
		if (method.TypeArguments.Length == 0)
			return false;

		if (target == IterationTarget.LegacyQuery)
		{
			if (IsReadWriteForEachMethodName(method.Name))
			{
				if (method.TypeArguments.Length == 2)
				{
					componentTypes = [method.TypeArguments[0], method.TypeArguments[1]];
					return true;
				}

				return false;
			}

			if (method.Name == "Run" && method.TypeArguments.Length > 1)
			{
				componentTypes = SkipTypeArguments(method.TypeArguments, 1);
				return true;
			}

			if (method.Name == "ForEach")
			{
				bool isJobGenericOverload = method.TypeParameters.Length > 0 &&
											string.Equals(
												method.TypeParameters[0].Name, "TJob", StringComparison.Ordinal
											);

				componentTypes = isJobGenericOverload
									 ? SkipTypeArguments(method.TypeArguments, 1)
									 : method.TypeArguments.ToArray();

				return componentTypes.Length > 0;
			}

			return false;
		}

		if (target == IterationTarget.QueryCursor || target == IterationTarget.QueryView)
		{
			if (method.Name == "ForEach")
			{
				componentTypes = method.TypeArguments.ToArray();
				return componentTypes.Length > 0;
			}

			if ((method.Name == "Run" || method.Name == "RunParallel") && method.TypeArguments.Length > 1)
			{
				componentTypes = SkipTypeArguments(method.TypeArguments, 1);
				return componentTypes.Length > 0;
			}

			return false;
		}

		if (target == IterationTarget.World)
		{
			if (method.Name == "ForEach" && method.TypeArguments.Length > 1)
			{
				componentTypes = SkipTypeArguments(method.TypeArguments, 1);
				return componentTypes.Length > 0;
			}

			if ((method.Name == "Run" || method.Name == "RunParallel") && method.TypeArguments.Length > 2)
			{
				componentTypes = SkipTypeArguments(method.TypeArguments, 2);
				return componentTypes.Length > 0;
			}
		}

		return false;
	}

	private static bool TryGetComponentTypesFromGenericName(
		GenericNameSyntax genericName,
		ITypeSymbol?      receiverType,
		SemanticModel     semanticModel,
		string            methodName,
		out ITypeSymbol[] componentTypes)
	{
		componentTypes = [];
		if (!TryResolveIterationTargetFromReceiverType(receiverType, out var target))
			return false;

		int skipCount = methodName switch
		{
			"ForEach" => target switch
			{
				IterationTarget.QueryCursor => 0,
				IterationTarget.QueryView   => 0,
				IterationTarget.World       => 1,
				IterationTarget.LegacyQuery => 0,
				_                           => int.MaxValue
			},
			"ForEachRead" => 0,
			"Run" or "RunParallel" => target switch
			{
				IterationTarget.QueryCursor => 1,
				IterationTarget.QueryView   => 1,
				IterationTarget.World       => 2,
				IterationTarget.LegacyQuery => 1,
				_                           => int.MaxValue
			},
			_ => int.MaxValue
		};

		if (skipCount >= genericName.TypeArgumentList.Arguments.Count)
			return false;

		var result = new List<ITypeSymbol>();
		for (int i = skipCount; i < genericName.TypeArgumentList.Arguments.Count; i++)
		{
			var type = semanticModel.GetTypeInfo(genericName.TypeArgumentList.Arguments[i]).Type;
			if (type is { })
				result.Add(type);
		}

		componentTypes = result.ToArray();
		return componentTypes.Length > 0;
	}

	private static bool TryGetComponentTypesFromJobParameter(
		IMethodSymbol     method,
		IMethodSymbol     originalMethod,
		out ITypeSymbol[] componentTypes)
	{
		componentTypes = [];
		var jobType = GetPotentialJobType(method, originalMethod);
		if (jobType is null)
			return false;

		var inferred = InferJobComponentTypes(jobType);
		if (inferred.Length == 0)
			return false;

		componentTypes = inferred;
		return true;
	}

	private static bool TryGetComponentTypesFromPotentialJobType(ITypeSymbol? jobType, out ITypeSymbol[] componentTypes)
	{
		componentTypes = [];
		if (jobType is null)
			return false;

		var inferred = InferJobComponentTypes(jobType);
		if (inferred.Length == 0)
			return false;

		componentTypes = inferred;
		return true;
	}

	private static bool TryGetDirectAccess(
		IMethodSymbol    method,
		out AccessTarget target,
		out bool         isWrite,
		out ITypeSymbol  accessedType)
	{
		target       = AccessTarget.None;
		isWrite      = false;
		accessedType = null!;
		var originalMethod = method.ReducedFrom ?? method;
		var candidate = method.TypeArguments.Length == 1
							? method
							: originalMethod.TypeArguments.Length == 1
								? originalMethod
								: null;

		if (candidate is null || candidate.TypeArguments.Length != 1)
			return false;

		string containingType = candidate.ContainingType.ToDisplayString();
		if (containingType != "Bezoro.ECS.Services.World" &&
			containingType != "Bezoro.ECS.Abstractions.IWorld")
			return false;

		accessedType = candidate.TypeArguments[0];
		switch (candidate.Name)
		{
			case "Read":
			case "TryRead":
			case "Get":
			case "TryGet":
			case "Has":
				target  = AccessTarget.Component;
				isWrite = false;
				return true;
			case "Write":
			case "TryWrite":
			case "Set":
			case "Replace":
			case "Add":
			case "Remove":
				target  = AccessTarget.Component;
				isWrite = true;
				return true;
			case "ReadResource":
			case "TryReadResource":
			case "GetResource":
			case "HasResource":
				target  = AccessTarget.Resource;
				isWrite = false;
				return true;
			case "WriteResource":
			case "GetOrCreateResource":
			case "SetResource":
			case "ReplaceResource":
			case "RemoveResource":
				target  = AccessTarget.Resource;
				isWrite = true;
				return true;
			default:
				return false;
		}
	}

	private static bool TryGetForEachComponentAccess(
		IMethodSymbol     method,
		out bool          isReadWrite,
		out ITypeSymbol[] componentTypes)
	{
		isReadWrite    = false;
		componentTypes = [];
		var originalMethod = method.ReducedFrom ?? method;

		if (!TryResolveIterationTarget(method, originalMethod, out var target))
			return false;

		if (IsReadWriteForEachMethodName(method.Name) || IsReadWriteForEachMethodName(originalMethod.Name))
		{
			if (method.TypeArguments.Length == 2)
			{
				isReadWrite    = true;
				componentTypes = [method.TypeArguments[0], method.TypeArguments[1]];
				return true;
			}

			return false;
		}

		if (TryGetComponentTypesFromGenericArguments(method, target, out componentTypes))
			return true;

		return TryGetComponentTypesFromJobParameter(method, originalMethod, out componentTypes);
	}

	private static bool TryGetSingleReadOnlyQueryViewForEachComponent(
		IMethodSymbol   method,
		out ITypeSymbol componentType)
	{
		componentType = null!;
		var originalMethod = method.ReducedFrom ?? method;
		if (!TryResolveIterationTarget(method, originalMethod, out var target) ||
			target != IterationTarget.QueryView)
			return false;

		if (method.Name != "ForEachRead" && originalMethod.Name != "ForEachRead")
			return false;

		if (method.TypeArguments.Length != 1)
			return false;

		if (!HasReadOnlyQueryViewForEachDelegate(method) && !HasReadOnlyQueryViewForEachDelegate(originalMethod))
			return false;

		componentType = method.TypeArguments[0];
		return true;
	}

	private static bool TryResolveIterationTarget(
		IMethodSymbol       method,
		IMethodSymbol       originalMethod,
		out IterationTarget target)
	{
		target = IterationTarget.None;
		if (!IsIterationMethodName(method.Name) && !IsIterationMethodName(originalMethod.Name))
			return false;

		if (IsTypeName(method.ContainingType,         "Bezoro.ECS.Types.Query") ||
			IsTypeName(originalMethod.ContainingType, "Bezoro.ECS.Types.Query"))
		{
			target = IterationTarget.LegacyQuery;
			return true;
		}

		if (IsTypeName(method.ContainingType,         "Bezoro.ECS.Types.QueryCursor") ||
			IsTypeName(originalMethod.ContainingType, "Bezoro.ECS.Types.QueryCursor"))
		{
			target = IterationTarget.QueryCursor;
			return true;
		}

		if (method.ContainingType is INamedTypeSymbol methodContainingType &&
			methodContainingType.Name == "QueryView" &&
			methodContainingType.ContainingNamespace.ToDisplayString() == "Bezoro.ECS.Types")
		{
			target = IterationTarget.QueryView;
			return true;
		}

		if (originalMethod.ContainingType is INamedTypeSymbol originalContainingType &&
			originalContainingType.Name == "QueryView" &&
			originalContainingType.ContainingNamespace.ToDisplayString() == "Bezoro.ECS.Types")
		{
			target = IterationTarget.QueryView;
			return true;
		}

		if (IsTypeName(method.ContainingType,         "Bezoro.ECS.Services.World") ||
			IsTypeName(originalMethod.ContainingType, "Bezoro.ECS.Services.World"))
		{
			target = IterationTarget.World;
			return true;
		}

		if (!originalMethod.IsExtensionMethod || originalMethod.Parameters.Length == 0)
			return false;

		var receiverType = originalMethod.Parameters[0].Type;
		if (IsTypeName(receiverType, "Bezoro.ECS.Types.Query"))
		{
			target = IterationTarget.LegacyQuery;
			return true;
		}

		if (IsTypeName(receiverType, "Bezoro.ECS.Types.QueryCursor"))
		{
			target = IterationTarget.QueryCursor;
			return true;
		}

		if (receiverType is INamedTypeSymbol receiverNamed &&
			receiverNamed.Name == "QueryView" &&
			receiverNamed.ContainingNamespace.ToDisplayString() == "Bezoro.ECS.Types")
		{
			target = IterationTarget.QueryView;
			return true;
		}

		if (IsTypeName(receiverType, "Bezoro.ECS.Services.World"))
		{
			target = IterationTarget.World;
			return true;
		}

		return false;
	}

	private static bool TryResolveIterationTargetFromReceiverType(ITypeSymbol? receiverType, out IterationTarget target)
	{
		target = IterationTarget.None;
		if (receiverType is null)
			return false;

		if (IsTypeName(receiverType, "Bezoro.ECS.Types.Query"))
		{
			target = IterationTarget.LegacyQuery;
			return true;
		}

		if (IsTypeName(receiverType, "Bezoro.ECS.Types.QueryCursor"))
		{
			target = IterationTarget.QueryCursor;
			return true;
		}

		if (receiverType is INamedTypeSymbol receiverNamed &&
			receiverNamed.Name == "QueryView" &&
			receiverNamed.ContainingNamespace.ToDisplayString() == "Bezoro.ECS.Types")
		{
			target = IterationTarget.QueryView;
			return true;
		}

		if (IsTypeName(receiverType, "Bezoro.ECS.Services.World"))
		{
			target = IterationTarget.World;
			return true;
		}

		return false;
	}

	private static ITypeSymbol? GetPotentialJobType(IMethodSymbol method, IMethodSymbol originalMethod)
	{
		for (var i = 0; i < method.Parameters.Length; i++)
		{
			var type = method.Parameters[i].Type;
			if (type.TypeKind == TypeKind.Delegate || IsQueryHandleType(type))
				continue;

			if (InferJobComponentTypes(type).Length > 0)
				return type;
		}

		int start = originalMethod.IsExtensionMethod ? 1 : 0;
		for (int i = start; i < originalMethod.Parameters.Length; i++)
		{
			var type = originalMethod.Parameters[i].Type;
			if (type.TypeKind == TypeKind.Delegate || IsQueryHandleType(type))
				continue;

			if (InferJobComponentTypes(type).Length > 0)
				return type;
		}

		return null;
	}

	private static ITypeSymbol[] InferJobComponentTypes(ITypeSymbol jobType)
	{
		var result = new List<ITypeSymbol>();
		if (jobType is not INamedTypeSymbol named)
			return [];

		for (var i = 0; i < named.AllInterfaces.Length; i++)
		{
			var iface = named.AllInterfaces[i];
			if (!iface.IsGenericType)
				continue;

			if (iface.Name != "IForEach" && iface.Name != "IForEachEntity")
				continue;

			if (iface.ContainingNamespace.ToDisplayString() != "Bezoro.ECS.Abstractions")
				continue;

			if (iface.TypeArguments.Length is < 1 or > 4)
				continue;

			result.AddRange(iface.TypeArguments);
			break;
		}

		return result.ToArray();
	}

	private static ITypeSymbol[] SkipTypeArguments(ImmutableArray<ITypeSymbol> typeArguments, int skipCount)
	{
		if (skipCount >= typeArguments.Length)
			return [];

		var result = new ITypeSymbol[typeArguments.Length - skipCount];
		for (int i = skipCount; i < typeArguments.Length; i++)
			result[i - skipCount] = typeArguments[i];

		return result;
	}

	private static SystemModel BuildSystemModel(INamedTypeSymbol type, Compilation compilation)
	{
		var reads          = new HashSet<string>(StringComparer.Ordinal);
		var writes         = new HashSet<string>(StringComparer.Ordinal);
		var readResources  = new HashSet<string>(StringComparer.Ordinal);
		var writeResources = new HashSet<string>(StringComparer.Ordinal);
		var isExclusive    = false;

		for (var current = type; current is { }; current = current.BaseType)
		{
			foreach (var attribute in current.GetAttributes())
			{
				var attributeClass = attribute.AttributeClass;
				if (attributeClass is null) continue;

				string namespaceName = attributeClass.ContainingNamespace.ToDisplayString();
				if (namespaceName != "Bezoro.ECS.Attributes")
					continue;

				if (attributeClass.Name == "ReadsAttribute" &&
					TryGetSingleAttributeTypeName(attribute, out var readTypeName))
					reads.Add(readTypeName);
				else if (attributeClass.Name == "WritesAttribute" &&
						 TryGetSingleAttributeTypeName(attribute, out var writeTypeName))
					writes.Add(writeTypeName);
				else if (attributeClass.Name == "ReadsResourceAttribute" &&
						 TryGetSingleAttributeTypeName(attribute, out var readResourceTypeName))
					readResources.Add(readResourceTypeName);
				else if (attributeClass.Name == "WritesResourceAttribute" &&
						 TryGetSingleAttributeTypeName(attribute, out var writeResourceTypeName))
					writeResources.Add(writeResourceTypeName);
				else if (attributeClass.Name == "ExclusiveAttribute")
					isExclusive = true;
			}
		}

		InferFromUpdateBodies(type, compilation, reads, writes, readResources, writeResources);

		return new(
			type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
			reads.OrderBy(static x => x, StringComparer.Ordinal).ToArray(),
			writes.OrderBy(static x => x, StringComparer.Ordinal).ToArray(),
			readResources.OrderBy(static x => x, StringComparer.Ordinal).ToArray(),
			writeResources.OrderBy(static x => x, StringComparer.Ordinal).ToArray(),
			isExclusive
		);
	}

	private static void AddDirectIterationConflictResource(
		HashSet<string> readResources,
		HashSet<string> writeResources)
	{
		writeResources.Add(DIRECT_ITERATION_CONFLICT_RESOURCE_KEY);
		readResources.Remove(DIRECT_ITERATION_CONFLICT_RESOURCE_KEY);
	}

	private static void AddReadComponent(HashSet<string> reads, HashSet<string> writes, ITypeSymbol type)
	{
		string key = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
		if (!writes.Contains(key))
			reads.Add(key);
	}

	private static void AddReadResource(
		HashSet<string> readResources,
		HashSet<string> writeResources,
		ITypeSymbol     type)
	{
		string key = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
		if (!writeResources.Contains(key))
			readResources.Add(key);
	}

	private static void AddWriteComponent(HashSet<string> reads, HashSet<string> writes, ITypeSymbol type)
	{
		string key = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
		writes.Add(key);
		reads.Remove(key);
	}

	private static void AddWriteResource(
		HashSet<string> readResources,
		HashSet<string> writeResources,
		ITypeSymbol     type)
	{
		string key = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
		writeResources.Add(key);
		readResources.Remove(key);
	}

	private static void CollectSystems(
		INamespaceSymbol         namespaceSymbol,
		Compilation              compilation,
		ICollection<SystemModel> output)
	{
		foreach (var member in namespaceSymbol.GetMembers())
		{
			if (member is INamespaceSymbol ns)
			{
				CollectSystems(ns, compilation, output);
				continue;
			}

			if (member is INamedTypeSymbol type)
				CollectSystems(type, compilation, output);
		}
	}

	private static void CollectSystems(INamedTypeSymbol type, Compilation compilation, ICollection<SystemModel> output)
	{
		if (type.TypeKind == TypeKind.Class || type.TypeKind == TypeKind.Struct)
			if (ImplementsSystem(type) && IsAccessibleFromGeneratedCode(type))
				output.Add(BuildSystemModel(type, compilation));

		var nestedTypes = type.GetTypeMembers();
		for (var i = 0; i < nestedTypes.Length; i++)
			CollectSystems(nestedTypes[i], compilation, output);
	}

	private static void InferFromInvocation(
		IMethodSymbol   method,
		HashSet<string> reads,
		HashSet<string> writes,
		HashSet<string> readResources,
		HashSet<string> writeResources)
	{
		var  originalMethod     = method.ReducedFrom ?? method;
		bool hasIterationTarget = TryResolveIterationTarget(method, originalMethod, out var iterationTarget);

		if (TryGetSingleReadOnlyQueryViewForEachComponent(method, out var readOnlyComponentType))
		{
			AddReadComponent(reads, writes, readOnlyComponentType);
			if (hasIterationTarget && RequiresDirectIterationConflict(iterationTarget))
				AddDirectIterationConflictResource(readResources, writeResources);

			return;
		}

		if (TryGetDirectAccess(method, out var target, out bool isWrite, out var accessedType))
		{
			if (target == AccessTarget.Component)
			{
				if (isWrite)
					AddWriteComponent(reads, writes, accessedType);
				else
					AddReadComponent(reads, writes, accessedType);
			}
			else if (target == AccessTarget.Resource)
			{
				if (isWrite)
					AddWriteResource(readResources, writeResources, accessedType);
				else
					AddReadResource(readResources, writeResources, accessedType);
			}

			return;
		}

		if (!TryGetForEachComponentAccess(method, out bool isReadWrite, out var componentTypes))
			return;

		if (componentTypes.Length == 0)
			return;

		if (isReadWrite)
		{
			for (var i = 0; i < componentTypes.Length; i++)
				AddWriteComponent(reads, writes, componentTypes[i]);

			if (hasIterationTarget && RequiresDirectIterationConflict(iterationTarget))
				AddDirectIterationConflictResource(readResources, writeResources);

			return;
		}

		AddWriteComponent(reads, writes, componentTypes[0]);
		for (var i = 1; i < componentTypes.Length; i++)
			AddReadComponent(reads, writes, componentTypes[i]);

		if (hasIterationTarget && RequiresDirectIterationConflict(iterationTarget))
			AddDirectIterationConflictResource(readResources, writeResources);
	}

	private static void InferFromInvocationSyntax(
		InvocationExpressionSyntax invocation,
		SemanticModel              semanticModel,
		HashSet<string>            reads,
		HashSet<string>            writes,
		HashSet<string>            readResources,
		HashSet<string>            writeResources)
	{
		if (semanticModel.GetOperation(invocation) is IInvocationOperation)
			return;

		if (invocation.Expression is not MemberAccessExpressionSyntax memberAccess)
			return;

		if (memberAccess.Name is not GenericNameSyntax and not IdentifierNameSyntax)
			return;

		string methodName = memberAccess.Name.Identifier.ValueText;
		if (methodName != "ForEach" &&
			methodName != "ForEachRead" &&
			methodName != "Run" &&
			methodName != "RunParallel")
			return;

		var receiverType = semanticModel.GetTypeInfo(memberAccess.Expression).Type;
		if (!TryResolveIterationTargetFromReceiverType(receiverType, out var target))
			return;

		if (methodName == "ForEachRead")
		{
			if (memberAccess.Name is not GenericNameSyntax readOnlyGenericName ||
				!TryGetComponentTypesFromGenericName(
					readOnlyGenericName, receiverType, semanticModel, methodName, out var readOnlyTypes
				) ||
				readOnlyTypes.Length != 1)
				return;

			AddReadComponent(reads, writes, readOnlyTypes[0]);
			if (RequiresDirectIterationConflict(target))
				AddDirectIterationConflictResource(readResources, writeResources);

			return;
		}

		if (methodName is "Run" or "RunParallel")
		{
			ITypeSymbol? jobType = null;
			for (var i = 0; i < invocation.ArgumentList.Arguments.Count; i++)
			{
				var candidateType = semanticModel.GetTypeInfo(invocation.ArgumentList.Arguments[i].Expression).Type;
				if (TryGetComponentTypesFromPotentialJobType(candidateType, out var componentTypes))
				{
					jobType = candidateType;
					AddWriteComponent(reads, writes, componentTypes[0]);
					for (var componentIndex = 1; componentIndex < componentTypes.Length; componentIndex++)
						AddReadComponent(reads, writes, componentTypes[componentIndex]);

					break;
				}
			}

			if (jobType is { })
			{
				if (RequiresDirectIterationConflict(target))
					AddDirectIterationConflictResource(readResources, writeResources);

				return;
			}
		}

		if (memberAccess.Name is not GenericNameSyntax genericName)
			return;

		if (!TryGetComponentTypesFromGenericName(
				genericName, receiverType, semanticModel, methodName, out var genericComponentTypes
			))
			return;

		AddWriteComponent(reads, writes, genericComponentTypes[0]);
		for (var i = 1; i < genericComponentTypes.Length; i++)
			AddReadComponent(reads, writes, genericComponentTypes[i]);

		if (RequiresDirectIterationConflict(target))
			AddDirectIterationConflictResource(readResources, writeResources);
	}

	private static void InferFromOperation(
		IOperation      root,
		HashSet<string> reads,
		HashSet<string> writes,
		HashSet<string> readResources,
		HashSet<string> writeResources)
	{
		var stack = new Stack<IOperation>();
		stack.Push(root);

		while (stack.Count > 0)
		{
			var current = stack.Pop();
			if (current is IInvocationOperation invocation)
				InferFromInvocation(invocation.TargetMethod, reads, writes, readResources, writeResources);

			foreach (var child in current.ChildOperations)
				stack.Push(child);
		}
	}

	private static void InferFromUpdateBodies(
		INamedTypeSymbol type,
		Compilation      compilation,
		HashSet<string>  reads,
		HashSet<string>  writes,
		HashSet<string>  readResources,
		HashSet<string>  writeResources)
	{
		var members = type.GetMembers("Update");
		for (var memberIndex = 0; memberIndex < members.Length; memberIndex++)
		{
			if (members[memberIndex] is not IMethodSymbol method)
				continue;

			for (var syntaxIndex = 0; syntaxIndex < method.DeclaringSyntaxReferences.Length; syntaxIndex++)
			{
				if (method.DeclaringSyntaxReferences[syntaxIndex].GetSyntax() is not MethodDeclarationSyntax syntax)
					continue;

				var         semanticModel = compilation.GetSemanticModel(syntax.SyntaxTree);
				IOperation? operation     = null;
				if (syntax.Body is { })
					operation = semanticModel.GetOperation(syntax.Body);
				else if (syntax.ExpressionBody?.Expression is { } expression)
					operation = semanticModel.GetOperation(expression);

				if (operation is null)
					continue;

				InferFromOperation(operation, reads, writes, readResources, writeResources);
				foreach (var invocation in syntax.DescendantNodes().OfType<InvocationExpressionSyntax>())
					InferFromInvocationSyntax(invocation, semanticModel, reads, writes, readResources, writeResources);
			}
		}
	}

	private enum AccessTarget
	{
		None,
		Component,
		Resource
	}

	private enum IterationTarget
	{
		None,
		LegacyQuery,
		QueryCursor,
		QueryView,
		World
	}

	private sealed class SystemModel(
		string                systemType,
		IReadOnlyList<string> reads,
		IReadOnlyList<string> writes,
		IReadOnlyList<string> readResources,
		IReadOnlyList<string> writeResources,
		bool                  isExclusive
	)
	{
		public bool                  IsExclusive    { get; } = isExclusive;
		public IReadOnlyList<string> ReadResources  { get; } = readResources;
		public IReadOnlyList<string> Reads          { get; } = reads;
		public IReadOnlyList<string> WriteResources { get; } = writeResources;
		public IReadOnlyList<string> Writes         { get; } = writes;

		public string SystemType { get; } = systemType;
	}

	private static bool TryGetSingleAttributeTypeName(AttributeData attribute, out string typeName)
	{
		typeName = string.Empty;
		if (TryGetSingleAttributeType(attribute, out var type))
		{
			typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
			return true;
		}

		return false;
	}

	private static bool TryGetSingleAttributeType(AttributeData attribute, out ITypeSymbol type)
	{
		type = null!;
		var attributeClass = attribute.AttributeClass;
		if (attributeClass is { TypeArguments.Length: 1 })
		{
			type = attributeClass.TypeArguments[0];
			return true;
		}

		if (attribute.ConstructorArguments.Length == 1 &&
			attribute.ConstructorArguments[0].Kind == TypedConstantKind.Type &&
			attribute.ConstructorArguments[0].Value is ITypeSymbol constructorType)
		{
			type = constructorType;
			return true;
		}

		return false;
	}
}
